### ISSUE TITLE
OpenWrt Package installation fails

### ISSUE THREAD

**Issue by upMKuhn** [imp1sh/ansible_managemynetwork#3]
When I try to install my packages. It works first time. Executing the playbook again throws an error. I assume it tries to install ""
> fatal: [openwrt_router]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "executable": null,
            "force": null,
            "name": [
                ""
            ],
            "state": "present",
            "update_cache": true
        }
    },

```
---
- name: Set up and configure routers
  hosts: routers
  become: true
  gather_facts: false

  tasks:
    - name: Ensure Python is installed
      ansible.builtin.include_role:
        name: python
    - name: Gather facts
      vars:
        ansible_user: root
      ansible.builtin.setup:
    - name: Install packages
      ansible.builtin.include_role:
        name: imp1sh.ansible_managemynetwork.ansible_openwrtpackages
      vars:
        openwrt_packages_installrole:
          - "nano"
          - "htop"
          - "stubby"

    - name: Configure router
      ansible.builtin.include_role:
        name: dhcp

```
